name: Build and Test

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]
  workflow_dispatch:

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  linux-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Build
      run: |
        VERSION="0.0.${{ github.run_number }}"
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        dotnet restore
        dotnet build --configuration Release /p:Version="$VERSION" --no-restore
    
    - name: Upload NuGet Package
      uses: actions/upload-artifact@v4
      with:
        name: nuget-package-v${{ env.VERSION }}
        path: NYaul/bin/Release/NYaul.*.nupkg
        retention-days: 30