name: Build and Test

on:
  push:
    branches: [ "*" ]

jobs:
  linux-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Build and Test
      run: |
        dotnet restore
        dotnet build --no-restore
        dotnet test --no-build --framework net8.0 --logger "trx;LogFileName=TestResults/test-results.trx" --results-directory TestResults
    
    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results-linux
        path: TestResults
        retention-days: 30

  windows-build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Setup VSTest
      uses: darenm/Setup-VSTest@v1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1

    - name: Restore NuGet Packages
      run: nuget restore NYaul.sln

    - name: Build Solution
      run: |
        msbuild NYaul.sln /p:Configuration=Release /p:Platform="Any CPU" /restore
        msbuild NYaul.Tests\NYaul.Tests.csproj /p:Configuration=Release /p:Platform="Any CPU" /t:Build /p:TargetFramework=net481

    - name: Create TestResults Directory
      run: mkdir TestResults -Force

    - name: Test .NET Framework
      run: |
        vstest.console.exe NYaul.Tests\bin\Release\net481\NYaul.Tests.dll /Logger:"trx;LogFileName=TestResults/net481-test-results.trx"

    - name: Test .NET Core
      run: dotnet test --no-build --configuration Release --framework net8.0 --logger "trx;LogFileName=TestResults/net8-test-results.trx" --results-directory TestResults

    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results-windows
        path: TestResults
        retention-days: 30
