name: Build and Test

on:
  push:
    branches: [ "*" ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - os: ubuntu-latest
            framework: net8.0
          - os: windows-latest
            framework: all
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Setup .NET Framework (Windows)
      if: matrix.os == 'windows-latest'
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          8.0.x
          4.8.1

    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: dotnet test --no-build --verbosity normal --framework net8.0 --logger "trx;LogFileName=TestResults/test-results.trx" --results-directory TestResults
      
    - name: Test (Windows)
      if: matrix.os == 'windows-latest'
      run: dotnet test --no-build --verbosity normal --logger "trx;LogFileName=TestResults/test-results.trx" --results-directory TestResults
      
    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results-${{ matrix.os }}
        path: TestResults
        retention-days: 30
