name: Package Testing

on:
  workflow_run:
    workflows: ["Build and Test"]
    types:
      - completed

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  test-package:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Download NuGet Package
      uses: actions/download-artifact@v4
      with:
        name: nuget-package
        path: packages
        github-token: ${{ secrets.GITHUB_TOKEN }}
        run-id: ${{ github.event.workflow_run.id }}

    - name: Setup Local NuGet Source
      run: |
        dotnet nuget add source ${{ github.workspace }}/packages --name local-packages
        
    - name: Prepare Test Project
      run: |
        cd NYaul.Tests
        dotnet remove reference ../NYaul/NYaul.csproj
        dotnet add package NYaul --source ${{ github.workspace }}/packages

    - name: Run Tests
      run: dotnet test NYaul.Tests/NYaul.Tests.csproj --configuration Release
